=== HendrickZhou/JavaABC/ProgrammingAssigns/assign9/dvds.dtd
<!ELEMENT DVDS (DVD*) >

<!ELEMENT DVD (release_year, title, performers, discs, price) >

<!ATTLIST DVD id CDATA #REQUIRED>

<!ELEMENT release_year (#PCDATA)>

<!ELEMENT title (#PCDATA)>

<!ELEMENT performers (performer*)>

<!ELEMENT performer (#PCDATA)>

<!ELEMENT discs (#PCDATA)>

<!ELEMENT price (#PCDATA)>

=== HendrickZhou/JavaABC/ProgrammingAssigns/assign9/dvds.xml
<?xml version="1.0"?><!DOCTYPE  DVDS SYSTEM "dvds.dtd"><DVDS><DVD id="1"><release_year>2002</release_year><title>Star  Wars: Attack of the Clones</title><performers><performer>Ewan  McGregor</performer><performer>Natalie  Portman</performer><performer>Hayden  Christensen</performer></performers><discs>2</discs><price>14.99</price></DVD><DVD id="2"><release_year>1999</release_year><title>Star  Wars: The Phantom Menace</title><performers><performer>Ewan  McGregor</performer><performer>Natalie  Portman</performer><performer>Hayden  Christensen</performer></performers><discs>2</discs><price>14.99</price></DVD><DVD id="3"><release_year>2005</release_year><title>Star  Wars: Revenge of the Sith</title><performers><performer>Ewan  McGregor</performer><performer>Natalie  Portman</performer><performer>Hayden  Christensen</performer></performers><discs>2</discs><price>14.99</price></DVD><DVD id="4"><release_year>1977</release_year><title>Star  Wars: A New Hope</title><performers><performer>Ewan  McGregor</performer><performer>Natalie  Portman</performer><performer>Hayden  Christensen</performer></performers><discs>2</discs><price>14.99</price></DVD><DVD id="5"><release_year>1980</release_year><title>Star  Wars: The Empire Strikes Back</title><performers><performer>Ewan  McGregor</performer><performer>Natalie  Portman</performer><performer>Hayden  Christensen</performer></performers><discs>2</discs><price>14.99</price></DVD><DVD id="6"><release_year>1983</release_year><title>Star  Wars: Return of the Jedi</title><performers><performer>Ewan  McGregor</performer><performer>Natalie  Portman</performer><performer>Hayden  Christensen</performer></performers><discs>2</discs><price>14.99</price></DVD></DVDS>
